In [1]:
import pandas as pd

### Dla Etapu 3

In [20]:
dfLilate2 = pd.read_csv("./../../../our_data/Etap5/Etap2/Etap2LiLatee.csv")
dfAdam2= pd.read_csv("./../../../our_data/Etap5/Etap2/adam/df_finall.csv")

/home/adam/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (16) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [21]:
dfAdam2

,emotions,id,categories,objects,Sad,Fear,Angry,Happy,Neutral,Surprise,categories_list,object_list,people,faces
0,[],tOpTQ3Fuf9s,"[['stretcher', 0.09478817], ['prison', 0.08772...","[['person', 0.9170731902122498], ['person', 0....",0,0,0,0,0,0,"['stretcher', 'prison', 'bearskin', 'suit', 't...","['person', 'person', 'person', 'person', 'pers...",25,0.0
1,[],k0DqRstCgj4,"[['theater curtain', 0.47661874], ['stage', 0....","[['person', 0.954002857208252], ['person', 0.4...",0,0,0,0,0,0,"['theater curtain', 'stage', 'barn', 'prison',...","['person', 'person', 'cell phone', 'cell phone...",8,0.0
2,[],1CYH4F1KCw8,"[['planetarium', 0.2688136], ['military unifor...","[['person', 0.9589637517929077], ['person', 0....",0,0,0,0,0,0,"['planetarium', 'military uniform', 'cinema', ...","['person', 'person', 'person', 'person', 'pers...",14,0.0
3,[],UdjEoGzXxmI,"[['radio telescope', 0.107818], ['jean', 0.096...","[['person', 0.9621104001998901], ['person', 0....",0,0,0,0,0,0,"['radio telescope', 'jean', 'cellular telephon...","['person', 'person', 'person', 'person', 'pers...",11,0.0
4,"['Sad', 'Sad', 'Neutral', 'Neutral']",cD8SYW8rjaQ,"[['sports car', 0.4145472], ['racer', 0.392479...","[['person', 0.9145326018333435], ['person', 0....",2,0,0,0,2,0,"['sports car', 'racer', 'cab', 'car wheel', 'p...","['person', 'person', 'car', 'person', 'person'...",12,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6501,"['Sad', 'Angry', 'Angry', 'Neutral', 'Angry', ...",WBIlusTGa5w,"[['coho', 0.08500227], ['barracouta', 0.080164...","[['person', 0.9805687069892883], ['person', 0....",3,1,4,1,2,0,"['coho', 'barracouta', 'suit', 'bulletproof ve...","['person', 'person', 'person', 'person', 'pers...",16,11.0
6502,[],eXjCcC7e1fk,"[['stage', 0.84550816], ['theater curtain', 0....","[['person', 0.2859192490577698], ['person', 0....",0,0,0,0,0,0,"['stage', 'theater curtain', 'spotlight', 'tor...","['person', 'person', 'person', 'person', 'pers...",60,0.0
6503,['Sad'],ganP0dyR3GI,"[['torch', 0.40831023], ['ski', 0.05857353], [...","[['person', 0.6036699414253235], ['suitcase', ...",1,0,0,0,0,0,"['torch', 'ski', 'tennis ball', 'sax', 'microp...","['person', 'suitcase', 'skis', 'bicycle', 'car...",5,1.0
6504,[],PDti1FMjPmA,"[['book jacket', 0.19738354], ['cash machine',...","[['person', 0.8915494680404663], ['person', 0....",0,0,0,0,0,0,"['book jacket', 'cash machine', 'television', ...","['person', 'person', 'person', 'person', 'pers...",19,0.0
6505,"['Happy', 'Angry']",r4DD6ZrZ3_4,"[['burrito', 0.22436675], ['spaghetti squash',...","[['person', 0.5744277834892273], ['person', 0....",0,0,1,1,0,0,"['burrito', 'spaghetti squash', 'plate', 'head...","['person', 'person', 'dining table', 'bowl']",2,2.0

In [22]:
df_finall = dfLilate2.merge(dfAdam2, how='outer', left_on='video_id', right_on='id')
df_finall = df_finall.drop(['id'], axis=1)
df_finall.to_csv("./../../../our_data/Etap5/Etap2/df_merged.csv",index=False)

In [19]:
list(df_finall.columns)

['video_id',
 'trending_date',
 'title',
 'channel_title',
 'category_id',
 'publish_time',
 'tags',
 'views',
 'likes',
 'dislikes',
 'comment_count',
 'thumbnail_link',
 'comments_disabled',
 'ratings_disabled',
 'video_error_or_removed',
 'description',
 'relatedTo',
 'pub_date',
 'pub_day_of_the_week',
 'pub_year',
 'pub_month',
 'pub_day',
 'pub_hour',
 'tren_date',
 'tren_day_of_the_week',
 'tren_year',
 'tren_month',
 'tren_day',
 'time_to_trend_in_days',
 'dislikes/likes',
 'likes/views',
 'dislikes/views',
 'comment_count/views',
 'increase_views',
 'increase_likes',
 'increase_dislikes',
 'increase_comms',
 'times_in_trend',
 'avg_views',
 'avg_likes',
 'avg_dislikes',
 'avg_comms',
 'avg_views_increase_per_hour',
 'n_of_tags',
 'title_clean',
 'title_length',
 'title_n_of_words',
 'title_capital_letters',
 'title_capital_letters_percent',
 'title_small_letters',
 'title_small_letters_percent',
 'title_punctuation',
 'title_punctuation_percent',
 'title_n_of_emojis',
 'desc_clean',
 'desc_length',
 'desc_n_of_words',
 'desc_capital_letters',
 'desc_capital_letters_percent',
 'desc_small_letters',
 'desc_small_letters_percent',
 'desc_punctuation',
 'desc_punctuation_percent',
 'desc_list_of_urls',
 'desc_n_of_urls',
 'desc_n_of_emojis',
 'isFacebook',
 'isTwitter',
 'isInstagram',
 'mean_r',
 'mean_g',
 'mean_b',
 'std_r',
 'std_g',
 'std_b',
 'hist_r',
 'hist_g',
 'hist_b',
 'mean_h',
 'mean_s',
 'mean_v',
 'std_h',
 'std_s',
 'std_v',
 'entropy',
 'thumb_ocr_text',
 'clean_thumb_ocr_text',
 'thumb_ocr_text_V2',
 'clean_thumb_ocr_text_V2',
 'bboxes',
 'avg_texts_coords',
 'avg_texts_coordX',
 'avg_texts_coordY',
 'ocr_sentiment_compound',
 'emotions',
 'categories',
 'objects',
 'Sad',
 'Fear',
 'Angry',
 'Happy',
 'Neutral',
 'Surprise',
 'categories_list',
 'object_list',
 'people',
 'faces']

In [42]:
# br_et3
dfUS_finall = us_et3.merge(dfUS, how='outer', left_on='video_id', right_on='id')
# dfGb_finall = dfGb_finall.merge(dfGb1, how='inner', left_on='video_id', right_on='video_id')
# dfUS_finall = dfUS_finall.merge(dfUS1, how='inner', left_on='video_id', right_on='video_id')
listaUS = dfUS_finall.loc[:, "video_id"].values


df_gb1 = dfGb1.loc[~dfGb1.video_id.isin(listaGb), :]
df_us1 = dfUS1.loc[~dfUS1.video_id.isin(listaUS), :]

dfGb_finall = pd.concat([df_gb1,dfGb_finall])
dfUS_finall = pd.concat([df_us1,dfUS_finall])


dfUS_finall = dfUS_finall.drop(['id'], axis=1)
dfUS_finall = dfUS_finall.loc[~dfUS_finall.video_id.isna(), :]
dfUS_finall = dfUS_finall.groupby(['video_id']).first()
dfUS_finall = dfUS_finall.loc[:, dfUS_finall.columns != "Unnamed: 0"]
dfUS_finall = dfUS_finall.reset_index()

dfGb_finall = dfGb_finall.drop(['id'], axis=1)
dfGb_finall = dfGb_finall.loc[~dfGb_finall.video_id.isna(), :]
dfGb_finall = dfGb_finall.groupby(['video_id']).first()
dfGb_finall = dfGb_finall.loc[:, dfGb_finall.columns != "Unnamed: 0"]
dfGb_finall = dfGb_finall.reset_index()
# print(result.shape) 
dfGb_finall.to_csv("../our_data/Etap3/GB_merged.csv",index=False)

dfUS_finall.to_csv("../our_data/Etap3/US_merged.csv",index=False)

In [44]:
# br_et3
dfGb_finall = br_et3.merge(dfGb, how='outer', left_on='video_id', right_on='id')
dfUS_finall = us_et3.merge(dfUS, how='outer', left_on='video_id', right_on='id')
# dfGb_finall = dfGb_finall.merge(dfGb1, how='inner', left_on='video_id', right_on='video_id')
# dfUS_finall = dfUS_finall.merge(dfUS1, how='inner', left_on='video_id', right_on='video_id')
listaGb = dfGb_finall.loc[:, "video_id"].values
listaUS = dfUS_finall.loc[:, "video_id"].values


df_gb1 = dfGb1.loc[~dfGb1.video_id.isin(listaGb), :]
df_us1 = dfUS1.loc[~dfUS1.video_id.isin(listaUS), :]

dfGb_finall = pd.concat([df_gb1,dfGb_finall])
dfUS_finall = pd.concat([df_us1,dfUS_finall])


dfUS_finall = dfUS_finall.drop(['id'], axis=1)
dfUS_finall = dfUS_finall.loc[~dfUS_finall.video_id.isna(), :]
dfUS_finall = dfUS_finall.groupby(['video_id']).first()
dfUS_finall = dfUS_finall.loc[:, dfUS_finall.columns != "Unnamed: 0"]
dfUS_finall = dfUS_finall.reset_index()

dfGb_finall = dfGb_finall.drop(['id'], axis=1)
dfGb_finall = dfGb_finall.loc[~dfGb_finall.video_id.isna(), :]
dfGb_finall = dfGb_finall.groupby(['video_id']).first()
dfGb_finall = dfGb_finall.loc[:, dfGb_finall.columns != "Unnamed: 0"]
dfGb_finall = dfGb_finall.reset_index()
# print(result.shape) 
dfGb_finall.to_csv("../our_data/Etap2/GB_merged.csv",index=False)

dfUS_finall.to_csv("../our_data/Etap2/US_merged.csv",index=False)

In [43]:
br_et3 = pd.read_csv("../our_data/Etap2/GB-Etap2.csv")
us_et3 = pd.read_csv("../our_data/Etap2/US-Etap2.csv")
dfGb= pd.read_csv("../our_data/Etap2/adam/dfGB_finall.csv")
dfUS= pd.read_csv("../our_data/Etap2/adam/dfUS_finall.csv")

dfGb1= pd.read_csv("../our_data/Etap1/GB.csv")
dfUS1= pd.read_csv("../our_data/Etap1/US.csv")

### Dla Etapu 2